name: Auto (reviewer, assignees) on (issue, PR)
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-assign:
    if: contains(github.event.issue.title, '주차')  || contains(github.event.pull_request.title, '주차')

    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/workflows/config/auto-assign-config.yml
